---
settings:
  name: Astra Control Center
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: release-notes/whats-new.html
  versions:
  - version-number: '24.02'
    url: "/astra-control-center"
  - version-number: '23.10'
    url: "/astra-control-center-2310"
  - version-number: '23.07'
    url: "/astra-control-center-2307"
  - version-number: '23.04'
    url: "/astra-control-center-2304"
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation Astra Control Center
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: concepts
  - section: use
  - section: use-acp
  - section: rest-api
  - section: support
  - title: Versions antérieures
    url: "/acc-earlier-versions.html"
  - title: FAQ
    url: "/get-started/faq.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
