---
sidebar: sidebar 
permalink: concepts/choose-class-and-size.html 
keywords: service level, storage class, storage classes, pv size, persistent volume size, volume size, bandwidth, performance, persistent, volume, kubernetes, containers 
summary: Le centre de contrôle Astra prend en charge les classes de stockage Trident basées sur le stockage ONTAP. Comprenez comment la classe de stockage et la taille de volume persistant peuvent vous aider à atteindre vos objectifs de performance. 
---
= Classes de stockage et taille de volume persistant
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
Astra Control Center prend en charge ONTAP en tant que système de stockage back-end.



== Présentation

Le centre de contrôle Astra est compatible avec les éléments suivants :

* *Classes de stockage Trident soutenues par ONTAP Storage* : si vous utilisez un back-end ONTAP, Astra Control Center permet d'importer le back-end ONTAP pour signaler diverses informations de surveillance.



NOTE: Les classes de stockage Trident doivent être préconfigurées en dehors du centre de contrôle Astra.



== Classes de stockage

Lorsque vous ajoutez un cluster à Astra Control Center, vous êtes invité à sélectionner une classe de stockage précédemment configurée sur ce cluster comme classe de stockage par défaut. Cette classe de stockage sera utilisée lorsqu'aucune classe de stockage n'est spécifiée dans une demande de volume persistant. La classe de stockage par défaut peut être modifiée à tout moment dans Astra Control Center et toute classe de stockage peut être utilisée à tout moment en spécifiant le nom de la classe de stockage dans le graphique ESV ou Helm. Assurez-vous de n'avoir qu'une seule classe de stockage par défaut définie pour votre cluster Kubernetes.



== Pour en savoir plus

* https://docs.netapp.com/us-en/trident/index.html["Documentation Astra Trident"^]

