---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: object storage, astra, buckets, s3, cr, custom resource 
summary: 'Il est essentiel d"ajouter des fournisseurs de compartiments de stockage objet pour sauvegarder les applications et le stockage persistant ou pour cloner les applications entre les clusters.' 
---
= Gestion des compartiments
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Un fournisseur de compartiments de stockage est essentiel pour la sauvegarde de vos applications et du stockage persistant, ou pour le clonage d'applications entre les clusters. Avec Astra Control Center, ajoutez un fournisseur de magasin d'objets comme destination de sauvegarde externe pour vos applications.

Il n'est pas nécessaire de cloner la configuration de vos applications et le stockage persistant vers le même cluster.

Utilisez l'un des fournisseurs de compartiments Amazon simple Storage Service (S3) suivants :

* NetApp ONTAP S3
* NetApp StorageGRID S3
* Microsoft Azure
* S3 générique
+

NOTE: Amazon Web Services (AWS) et Google Cloud Platform (GCP) utilisent le type de compartiment S3 générique.

+

NOTE: Bien qu'Astra Control Center prenne en charge Amazon S3 en tant que fournisseur de compartiments génériques, Astra Control Center peut ne pas prendre en charge tous les fournisseurs de magasins d'objets qui affirment la prise en charge d'Amazon S3.



Un godet peut être dans l'un des États suivants :

* En attente : le compartiment est planifié pour la découverte.
* Disponible : le godet est disponible.
* Retiré : le godet n'est pas accessible actuellement.


Pour plus d'informations sur la gestion des compartiments à l'aide de l'API de contrôle Astra, reportez-vous au link:https://docs.netapp.com/us-en/astra-automation/["Informations sur l'automatisation et les API d'Astra"^].

Vous pouvez effectuer les tâches suivantes liées à la gestion des compartiments :

* link:../get-started/add-bucket.html["Ajouter un godet"]
* <<Modifier un godet>>
* <<Définir le compartiment par défaut>>
* <<Faire pivoter ou supprimer les identifiants de compartiment>>
* <<Déposer un godet>>
* link:../use/manage-buckets.html#manage-a-bucket-using-a-custom-resource["(Aperçu technique) Gérez un compartiment à l'aide d'une ressource personnalisée"]



NOTE: Les compartiments S3 du centre de contrôle Astra n'indiquent pas la capacité disponible. Avant de sauvegarder ou de cloner des applications gérées par Astra Control Center, vérifiez les informations de compartiment dans le système de gestion ONTAP ou StorageGRID.



== Modifier un godet

Vous pouvez modifier les informations d'identification d'accès pour un compartiment et modifier si un compartiment sélectionné est le compartiment par défaut.


NOTE: Lorsque vous ajoutez un compartiment, sélectionnez le fournisseur approprié et fournissez les identifiants appropriés pour ce fournisseur. Par exemple, l'interface utilisateur accepte NetApp ONTAP S3 comme type et accepte les identifiants StorageGRID. Toutefois, toutes les futures sauvegardes et restaurations des applications à l'aide de ce compartiment échoueront. Voir la link:../release-notes/known-issues.html#selecting-a-bucket-provider-type-with-credentials-for-another-type-causes-data-protection-failures["Notes de version"].

.Étapes
. Dans le menu de navigation de gauche, sélectionnez *seaux*.
. Dans le menu de la colonne *actions*, sélectionnez *Modifier*.
. Modifier toute information autre que le type de godet.
+

TIP: Vous ne pouvez pas modifier le type de compartiment.

. Sélectionnez *mettre à jour*.




== Définir le compartiment par défaut

Lorsque vous effectuez un clone entre les clusters, Astra Control requiert un compartiment par défaut. La procédure suivante permet de définir un compartiment par défaut pour l'ensemble des clusters.

.Étapes
. Accédez à *Cloud instances*.
. Sélectionnez le menu dans la colonne *actions* pour l'instance de Cloud dans la liste.
. Sélectionnez *Modifier*.
. Dans la liste *godet*, sélectionnez le compartiment par défaut.
. Sélectionnez *Enregistrer*.




== Faire pivoter ou supprimer les identifiants de compartiment

Astra Control utilise des identifiants de compartiment pour accéder à ce compartiment et fournit des clés secrètes pour le compartiment S3 afin qu'Astra Control Center puisse communiquer avec le compartiment.



=== Faire pivoter les identifiants du godet

Si vous faites pivoter les informations d'identification, faites-les pivoter pendant une fenêtre de maintenance lorsqu'aucune sauvegarde n'est en cours (planifiée ou à la demande).

.Procédure de modification et de rotation des informations d'identification
. Dans le menu de navigation de gauche, sélectionnez *seaux*.
. Dans le menu Options de la colonne *actions*, sélectionnez *Modifier*.
. Créer les nouvelles informations d'identification.
. Sélectionnez *mettre à jour*.




=== Supprimer les identifiants du compartiment

Le retrait des identifiants de compartiment est uniquement possible si de nouvelles informations d'identification ont été appliquées à un compartiment ou si ce dernier n'est plus utilisé activement.


TIP: Le premier ensemble d'informations d'identification que vous ajoutez à Astra Control est toujours utilisé car Astra Control utilise les informations d'identification pour authentifier le compartiment de secours. Ne pas supprimer ces identifiants si le compartiment est en cours d'utilisation, car cela entraînera des défaillances de sauvegarde et des problèmes d'indisponibilité des sauvegardes.


NOTE: Si vous supprimez les identifiants de compartiment actifs, reportez-vous à la section https://kb.netapp.com/Cloud/Astra/Control/Deleting_active_S3_bucket_credentials_leads_to_spurious_500_errors_reported_in_the_UI["dépannage de la dépose des informations d'identification du godet"].

Pour obtenir des instructions sur la suppression des informations d'identification S3 à l'aide de l'API de contrôle Astra, reportez-vous au link:https://docs.netapp.com/us-en/astra-automation/["Informations sur l'automatisation et les API d'Astra"^].



== Déposer un godet

Il est possible de retirer un godet qui n'est plus utilisé ou qui n'est pas en bon état. Pour simplifier et à jour la configuration du magasin d'objets,

[NOTE]
====
* Vous ne pouvez pas supprimer un compartiment par défaut. Si vous souhaitez retirer ce compartiment, sélectionnez tout d'abord un autre compartiment comme valeur par défaut.
* Vous ne pouvez pas supprimer un compartiment WORM (Write Once, Read Many) avant l'expiration de la période de conservation du fournisseur cloud du compartiment. Les godets À VIS SANS FIN sont signalés par « verrouillé » à côté du nom du compartiment.


====
* Vous ne pouvez pas supprimer un compartiment par défaut. Si vous souhaitez retirer ce compartiment, sélectionnez tout d'abord un autre compartiment comme valeur par défaut.


.Avant de commencer
* Avant de commencer, assurez-vous qu'aucune sauvegarde n'est en cours d'exécution ou terminée pour ce compartiment.
* Vérifiez que le godet n'est pas utilisé dans le cadre d'une politique de protection active.


Si c'est le cas, vous ne pourrez pas continuer.

.Étapes
. Dans la navigation à gauche, sélectionnez *seaux*.
. Dans le menu *actions*, sélectionnez *Supprimer*.
+

NOTE: Astra Control veille à l'absence de règles de planification qui utilise le compartiment pour les sauvegardes et à l'absence de sauvegardes actives dans le compartiment.

. Tapez « Supprimer » pour confirmer l'action.
. Sélectionnez *Oui, retirez le godet*.




== [Aperçu technique] Gérez un compartiment à l'aide d'une ressource personnalisée

Vous pouvez ajouter un compartiment à l'aide d'une ressource personnalisée Astra Control (CR) sur le cluster d'applications. Il est essentiel d'ajouter des fournisseurs de compartiments de stockage objet pour sauvegarder les applications et le stockage persistant ou pour cloner les applications entre les clusters. Astra Control stocke les sauvegardes ou les clones dans les compartiments de magasin d'objets que vous définissez. Si vous utilisez la méthode de ressources personnalisées, la fonctionnalité de snapshots d'applications requiert un compartiment.

Si vous clonez la configuration de vos applications et le stockage persistant vers le même cluster, il n'est pas nécessaire d'utiliser un compartiment dans Astra Control.

La ressource personnalisée du compartiment pour Astra Control est appelée AppVault. Ce CR contient les configurations nécessaires à l'utilisation d'un godet dans les opérations de protection.

.Avant de commencer
* Assurez-vous que vous disposez d'un compartiment accessible depuis vos clusters gérés par Astra Control Center.
* Vérifiez que vous disposez des informations d'identification pour le compartiment.
* S'assurer que le godet est de l'un des types suivants :
+
** NetApp ONTAP S3
** NetApp StorageGRID S3
** Microsoft Azure
** S3 générique





NOTE: Amazon Web Services (AWS) et Google Cloud Platform (GCP) utilisent le type de compartiment S3 générique.


NOTE: Bien qu'Astra Control Center prenne en charge Amazon S3 en tant que fournisseur de compartiments génériques, Astra Control Center peut ne pas prendre en charge tous les fournisseurs de magasins d'objets qui affirment la prise en charge d'Amazon S3.

.Étapes
. Créer le fichier de ressource personnalisée (CR) et le nommer (par exemple, `astra_appvault.yaml`).
. Configurez les attributs suivants :
+
** *metadata.name*: _(obligatoire)_ le nom de la ressource personnalisée AppVault.
** *Spec.prefix*: _(Facultatif)_ chemin précédé des noms de toutes les entités stockées dans le AppVault.
** *spec.providerConfig*: _(obligatoire)_ stocke la configuration nécessaire pour accéder à AppVault à l'aide du fournisseur spécifié.
** *spec.providerCredentials*: _(Facultatif)_ stocke les références à toute information d'identification requise pour accéder à AppVault à l'aide du fournisseur spécifié.
+
*** *spec.providerCredentials.valueFromSecret*: _(Facultatif)_ indique que la valeur d'identification doit provenir d'un secret.
+
**** *Key*: _(requis si valueFromSecret est utilisé)_ la clé valide du secret à sélectionner.
**** *Nom*: _(requis si valueFromSecret est utilisé)_ Nom du secret contenant la valeur de ce champ. Doit être dans le même espace de noms.




** *spec.providerType*: _(obligatoire)_ détermine ce qui fournit la sauvegarde, par exemple S3 ou le système de fichiers.
+
Exemple YAML :

+
[source, yaml]
----
apiVersion: astra.netapp.io/v1
kind: AppVault
metadata:
  name: astra_appvault
spec:
  providerType: generic-s3
  providerConfig:
    path: testpath
    endpoint: 192.168.1.100:80
    bucketName: bucket1
    secure: "false"
  providerCredentials:
    accessKeyID:
      valueFromSecret:
        name: s3-creds
        key: accessKeyID
    secretAccessKey:
      valueFromSecret:
        name: s3-creds
        key: secretAccessKey
----


. Après avoir renseigné le `astra_appvault.yaml` Fichier avec les valeurs correctes, appliquer la CR :
+
[source, console]
----
kubectl apply -f astra_appvault.yaml -n neptune-system
----
+

NOTE: Lorsque vous ajoutez un godet, Astra Control marque un godet avec l'indicateur de compartiment par défaut. Le premier compartiment que vous créez devient le compartiment par défaut. Au fur et à mesure que vous ajoutez des compartiments, vous pourrez décider plus tard link:../use/manage-buckets.html#set-the-default-bucket["définir un autre compartiment par défaut"^].





== Trouvez plus d'informations

* https://docs.netapp.com/us-en/astra-automation["Utilisez l'API de contrôle Astra"^]

