---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: 'Ajoutez et supprimez des informations d"identification du fournisseur cloud de votre compte à tout moment. Astra utilise ces identifiants pour provisionner des ressources en votre nom.' 
---
= Ajouter et supprimer des informations d'identification
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Ajoutez et supprimez des identifiants pour les fournisseurs de cloud privé local, comme ONTAP S3, les clusters Kubernetes gérés avec OpenShift ou les clusters Kubernetes non gérés depuis votre compte à tout moment. Astra Control Center utilise ces identifiants pour détecter les clusters Kubernetes et les applications sur les clusters et provisionner les ressources en votre nom.

Notez que tous les utilisateurs d'Astra Control Center partagent les mêmes informations d'identification.



== Ajouter des informations d'identification

Vous pouvez ajouter des informations d'identification à Astra Control Center lorsque vous gérez des clusters. Pour ajouter des informations d'identification en ajoutant un nouveau cluster, reportez-vous à la section link:../get-started/setup_overview.html#add-cluster["Ajouter un cluster Kubernetes"].


IMPORTANT: Si vous créez la vôtre `kubeconfig` fichier, vous ne devez définir que *un* élément de contexte dans celui-ci. Voir https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["Documentation Kubernetes"^] pour plus d'informations sur la création `kubeconfig` fichiers.



== Supprimer les informations d'identification

Supprimez les informations d'identification d'un compte à tout moment. Vous ne devez supprimer les informations d'identification qu'après link:unmanage.html["annuler la gestion de tous les clusters associés"].


NOTE: Le premier ensemble d'informations d'identification que vous ajoutez à Astra Control Center est toujours utilisé car Astra Control Center utilise les informations d'identification pour s'authentifier auprès du compartiment de secours. Il est préférable de ne pas supprimer ces informations d'identification.

.Étapes
. Sélectionnez *compte*.
. Sélectionnez l'onglet *informations d'identification*.
. Sélectionnez le menu Options dans la colonne *État* pour les informations d'identification que vous souhaitez supprimer.
. Sélectionnez *Supprimer*.
. Tapez le mot "supprimer" pour confirmer la suppression, puis sélectionnez *Oui, Supprimer les informations d'identification*.


Astra Control Center supprime les informations d'identification du compte.
