---
sidebar: sidebar 
permalink: use/uninstall_acc.html 
keywords: astra, astra control center, uninstall, remove 
summary: Décrit comment retirer le centre de contrôle Astra et le conducteur du centre de contrôle Astra. 
---
= Désinstaller Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Vous devrez peut-être retirer les composants du centre de contrôle Astra si vous effectuez une mise à niveau d'un essai vers une version complète du produit. Pour déposer le centre de commande Astra et le conducteur du centre de commande Astra, exécuter les commandes décrites dans cette procédure dans l'ordre.

Si vous rencontrez des problèmes avec la désinstallation, reportez-vous à la section  uninstall issues.

.Ce dont vous avez besoin, 8217;ll
* Utilisez l'interface utilisateur d'Astra Control Center pour tout supprimer link:../use/unmanage.html#stop-managing-compute["clusters"].


.Étapes
. Supprimer Astra Control Center. L'exemple de commande suivant est basé sur une installation par défaut. Modifiez la commande si vous avez créé des configurations personnalisées.
+
[listing]
----
kubectl delete -f astra_control_center_min.yaml -n netapp-acc
----
+
Résultat :

+
[listing]
----
astracontrolcenter.astra.netapp.io "astra" deleted
----
. Utiliser la commande suivante pour supprimer le `netapp-acc` espace de noms :
+
[listing]
----
kubectl delete ns netapp-acc
----
+
Résultat :

+
[listing]
----
namespace "netapp-acc" deleted
----
. Utiliser la commande suivante pour supprimer les composants du système de l'opérateur Astra Control Center :
+
[listing]
----
kubectl delete -f astra_control_center_operator_deploy.yaml
----
+
Résultat :

+
[listing]
----
namespace/netapp-acc-operator deleted
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io deleted
role.rbac.authorization.k8s.io/acc-operator-leader-election-role deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role deleted
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding deleted
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding deleted
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding deleted
configmap/acc-operator-manager-config deleted
service/acc-operator-controller-manager-metrics-service deleted
deployment.apps/acc-operator-controller-manager deleted
----




== Dépannage des problèmes de désinstallation

Utilisez les solutions de contournement suivantes pour résoudre les problèmes que vous rencontrez lors de la désinstallation d'Astra Control Center.



=== La désinstallation d'Astra Control Center ne parvient pas à nettoyer le module de l'opérateur de surveillance sur le cluster géré

Si vous n'avez pas dégéré les clusters avant de désinstaller Astra Control Center, vous pouvez supprimer manuellement les pods dans l'espace de noms netapp-Monitoring et dans l'espace de noms à l'aide des commandes suivantes :

.Étapes
. Supprimer `acc-monitoring` agent :
+
[listing]
----
kubectl delete agents acc-monitoring -n netapp-monitoring
----
+
Résultat :

+
[listing]
----
agent.monitoring.netapp.com "acc-monitoring" deleted
----
. Supprimez le namespace :
+
[listing]
----
kubectl delete ns netapp-monitoring
----
+
Résultat :

+
[listing]
----
namespace "netapp-monitoring" deleted
----
. Confirmer la suppression des ressources :
+
[listing]
----
kubectl get pods -n netapp-monitoring
----
+
Résultat :

+
[listing]
----
No resources found in netapp-monitoring namespace.
----
. Confirmer la suppression de l'agent de surveillance :
+
[listing]
----
kubectl get crd|grep agent
----
+
Résultat de l'échantillon :

+
[listing]
----
agents.monitoring.netapp.com                     2021-07-21T06:08:13Z
----
. Supprimer les informations de définition de ressource personnalisée (CRD) :
+
[listing]
----
kubectl delete crds agents.monitoring.netapp.com
----
+
Résultat :

+
[listing]
----
customresourcedefinition.apiextensions.k8s.io "agents.monitoring.netapp.com" deleted
----




=== La désinstallation d'Astra Control Center ne parvient pas à nettoyer les CRD Traefik

Vous pouvez supprimer manuellement les CRD Traefik. Les CRDS sont des ressources globales, et leur suppression peut avoir un impact sur d'autres applications du cluster.

.Étapes
. Lister les CRD Traefik installés sur le cluster :
+
[listing]
----
kubectl get crds |grep -E 'traefik'
----
+
Réponse

+
[listing]
----
ingressroutes.traefik.containo.us             2021-06-23T23:29:11Z
ingressroutetcps.traefik.containo.us          2021-06-23T23:29:11Z
ingressrouteudps.traefik.containo.us          2021-06-23T23:29:12Z
middlewares.traefik.containo.us               2021-06-23T23:29:12Z
middlewaretcps.traefik.containo.us            2021-06-23T23:29:12Z
serverstransports.traefik.containo.us         2021-06-23T23:29:13Z
tlsoptions.traefik.containo.us                2021-06-23T23:29:13Z
tlsstores.traefik.containo.us                 2021-06-23T23:29:14Z
traefikservices.traefik.containo.us           2021-06-23T23:29:15Z
----
. Supprimez les CRD :
+
[listing]
----
kubectl delete crd ingressroutes.traefik.containo.us ingressroutetcps.traefik.containo.us ingressrouteudps.traefik.containo.us middlewares.traefik.containo.us serverstransports.traefik.containo.us tlsoptions.traefik.containo.us tlsstores.traefik.containo.us traefikservices.traefik.containo.us middlewaretcps.traefik.containo.us
----




== Trouvez plus d'informations

* link:../release-notes/known-issues.html["Problèmes connus de désinstallation"]

