---
sidebar: sidebar 
permalink: use/upgrade-acc.html 
keywords: astra upgrade, upgrade astra control center, how to upgrade astra control, update 
summary: Pour mettre à niveau Astra Control Center, téléchargez le pack et mettez-le à niveau en suivant les étapes décrites. 
---
= Mettez à niveau Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Pour mettre à niveau Astra Control Center, téléchargez le pack d'installation depuis le site de support NetApp et suivez ces instructions. Vous pouvez utiliser cette procédure pour mettre à niveau Astra Control Center dans des environnements connectés à Internet ou à air comprimé.

.Ce dont vous avez besoin, 8217;ll
* Avant de procéder à la mise à niveau, reportez-vous à la section link:../get-started/requirements.html#operational-environment-requirements["De l'environnement opérationnel"^] Pour garantir que votre environnement respecte les exigences minimales en matière de déploiement d'Astra Control Center. Votre environnement doit disposer des éléments suivants :
+
** Une version d'Astra Trident prise en charge pour déterminer la version que vous exécutez, exécutez la commande suivante contre votre Astra Control Center existant :
+
[listing]
----
../../trident-installer/tridentctl -n trident version
----
+
Reportez-vous à la section https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html#determine-the-version-to-upgrade-to["Documentation Astra Trident"] pour effectuer une mise à niveau à partir d'une ancienne version.

+

WARNING: Vous devez effectuer une mise à niveau vers Astra Trident 22.10 * AVANT* pour la mise à niveau vers Kubernetes 1.25.

** Une distribution Kubernetes prise en charge pour déterminer la version que vous exécutez, exécutez la commande suivante par rapport à votre Astra Control Center existant : `kubectl get nodes -o wide`
** Suffisamment de ressources de cluster pour déterminer les ressources de cluster, exécutez la commande suivante dans votre cluster Astra Control Center existant : `kubectl describe node <node name>`
** Registre que vous pouvez utiliser pour diffuser et télécharger des images Astra Control Center
** Une classe de stockage par défaut pour déterminer votre classe de stockage par défaut, exécutez la commande suivante avec votre Astra Control Center existant : `kubectl get storageclass`


* (OpenShift uniquement) Assurez-vous que tous les opérateurs de cluster sont en bon état et disponibles.
+
[listing]
----
kubectl get clusteroperators
----
* Assurez-vous que tous les services API sont dans un état sain et disponibles.
+
[listing]
----
kubectl get apiservices
----
* Déconnectez-vous de l'interface utilisateur de l'Astra Control Center avant de commencer la mise à niveau.


Le processus de mise à niveau d'Astra Control Center vous guide à travers les étapes de haut niveau suivantes :

*  the Astra Control Center bundle
*  the bundle
*  the images to your local registry
*  the updated Astra Control Center operator
*  Astra Control Center
*  system status



IMPORTANT: Ne supprimez pas l'opérateur du centre de contrôle Astra (par exemple, `kubectl delete -f astra_control_center_operator_deploy.yaml`) À tout moment pendant la mise à niveau ou l'opération Astra Control Center pour éviter de supprimer des modules.


TIP: Effectuez les mises à niveau dans une fenêtre de maintenance lorsque les planifications, les sauvegardes et les snapshots ne sont pas en cours d'exécution.



== Téléchargez le pack Astra Control Center

. Téléchargez le pack Astra Control Center à partir du https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["Site de support NetApp"^]. Le nom de fichier est similaire à ce qui suit : `astra-control-center-[version].tar.gz`.
. (Facultatif) Vérifiez la signature du lot :
+
[listing]
----
openssl dgst -sha256 -verify AstraControlCenter-public.pub -signature astra-control-center-[version].tar.gz.sig astra-control-center-[version].tar.gz
----




== Déballez le paquet

. Extraire les images :
+
[listing]
----
tar -vxzf astra-control-center-[version].tar.gz
----




== Vérifiez que vous avez installé le plug-in NetApp Astra kubectl

Le plug-in de ligne de commande NetApp Astra kubectl permet de gagner du temps lors de l'exécution des tâches courantes associées au déploiement et à la mise à niveau d'Astra Control Center.

. Utilisez la commande suivante pour déterminer si le plug-in est installé :
+
[listing]
----
kubectl astra
----


Cette commande doit fournir l'aide du plug-in kubectl. Si la commande renvoie une erreur, installez le plug-in à l'aide de ces éléments link:../get-started/install_acc.html#install-the-netapp-astra-kubectl-plugin["instructions"].



== Ajoutez les images à votre registre local

. Suivez la séquence d'étapes appropriée pour votre moteur de mise en conteneurs :


[role="tabbed-block"]
====
.Docker
--
. Passez à l' `acc` répertoire extrait du bundle tar :
+
Exemple :



[listing]
----
cd ../acc
----
. Envoyez les images du package dans le répertoire d'images Astra Control Center vers votre registre local. Exécutez les substitutions suivantes avant d'exécuter la commande :
+
** Remplacez <BUNDLE_FILE> par le nom du fichier bundle Astra Control (`acc.manifest.yaml`).
** Remplacer <MY_FULL_REGISTRY_PATH> par l'URL du référentiel Docker, par exemple https://exampledownloads.jfrog.io/docker-astra-control/v1/[].
** Remplacez <MY_REGISTRY_USER> par le nom d'utilisateur.
** Remplacez <MY_REGISTRY_TOKEN> par un jeton autorisé pour le registre.
+
[source, console]
----
kubectl astra packages push-images -m <BUNDLE_FILE> -r <MY_FULL_REGISTRY_PATH> -u <MY_REGISTRY_USER> -p <MY_REGISTRY_TOKEN>
----




--
.Podman
--
. Connectez-vous à votre registre :
+
[source, console]
----
podman login <MY_FULL_REGISTRY_PATH>
----
. Exécutez le script suivant, en procédant à la substitution <YOUR_REGISTRY> comme indiqué dans les commentaires :
+
[source, console]
----
# You need to be at the root of the tarball.
# You should see these files to confirm correct location:
#   acc.manifest.yaml
#   acc/

# Replace <YOUR_REGISTRY> with your own registry (e.g registry.customer.com or registry.customer.com/testing, etc..)
export REGISTRY=<YOUR_REGISTRY>
export PACKAGENAME=acc
export PACKAGEVERSION=22.11.0-82
export DIRECTORYNAME=acc
for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do
  # Load to local cache
  astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image(s): //')

  # Remove path and keep imageName.
  astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')

  # Tag with local image repo.
  podman tag ${astraImage} ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}

  # Push to the local repo.
  podman push ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done
----


--
====


== Poser le conducteur du centre de commande Astra mis à jour

. Modifier le répertoire :
+
[listing]
----
cd manifests
----
. Modifiez le yaml de déploiement de l'opérateur Astra Control Center (`astra_control_center_operator_deploy.yaml`) pour faire référence à votre registre local et à votre secret.
+
[listing]
----
vim astra_control_center_operator_deploy.yaml
----
+
.. Si vous utilisez un registre qui nécessite une authentification, remplacez ou modifiez la ligne par défaut de `imagePullSecrets: []` avec les éléments suivants :
+
[listing]
----
imagePullSecrets:
- name: <astra-registry-cred_or_custom_name_of_secret>
----
.. Changer `[your_registry_path]` pour le `kube-rbac-proxy` image dans le chemin du registre où vous avez poussé les images dans un  the images to your local registry,étape précédente.
.. Changer `[your_registry_path]` pour le `acc-operator` image dans le chemin du registre où vous avez poussé les images dans un  the images to your local registry,étape précédente.
.. Ajoutez les valeurs suivantes à la `env` section :
+
[listing]
----
- name: ACCOP_HELM_UPGRADETIMEOUT
  value: 300m
----
+
[listing, subs="+quotes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: [your_registry_path]/kube-rbac-proxy:v4.8.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        *- name: ACCOP_HELM_UPGRADETIMEOUT*
          *value: 300m*
        *image: [your_registry_path]/acc-operator:[version x.y.z]*
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 750Mi
          requests:
            cpu: 100m
            memory: 75Mi
        securityContext:
          allowPrivilegeEscalation: false
      *imagePullSecrets: []*
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
----


. Installez le nouveau conducteur du centre de contrôle Astra :
+
[listing]
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----
+
Exemple de réponse :

+
[listing]
----
namespace/netapp-acc-operator unchanged
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io configured
role.rbac.authorization.k8s.io/acc-operator-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role configured
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role unchanged
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding configured
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding unchanged
configmap/acc-operator-manager-config unchanged
service/acc-operator-controller-manager-metrics-service unchanged
deployment.apps/acc-operator-controller-manager configured
----
. Vérifiez que les pods sont en cours d'exécution :
+
[listing]
----
kubectl get pods -n netapp-acc-operator
----




== Mettez à niveau Astra Control Center

. Modifiez la ressource personnalisée Astra Control Center (CR) :
+
[listing]
----
kubectl edit AstraControlCenter -n [netapp-acc or custom namespace]
----
. Modifier le numéro de version de l'Astra (`astraVersion` intérieur de `Spec`) vers la version que vous mettez à niveau vers :
+
[listing, subs="+quotes"]
----
spec:
  accountName: "Example"
  *astraVersion: "[Version number]"*
----
. Vérifiez que le chemin du registre d'images correspond au chemin du registre vers lequel vous avez poussé les images dans un  the images to your local registry,étape précédente. Mise à jour `imageRegistry` intérieur de `Spec` si le registre a changé depuis votre dernière installation.
+
[listing]
----
  imageRegistry:
    name: "[your_registry_path]"
----
. Ajoutez les éléments suivants à votre `CRDs` configuration à l'intérieur de `Spec`:
+
[listing]
----
crds:
  shouldUpgrade: true
----
. Ajoutez les lignes suivantes dans `additionalValues` intérieur de `Spec` Dans le CR Astra Control Center :
+
[listing]
----
additionalValues:
    nautilus:
      startupProbe:
        periodSeconds: 30
        failureThreshold: 600
----
+
Une fois que vous avez enregistré et quitté l'éditeur de fichiers, les modifications seront appliquées et la mise à niveau commencera.

. (Facultatif) Vérifiez que les modules se terminent et deviennent disponibles à nouveau :
+
[listing]
----
watch kubectl get pods -n [netapp-acc or custom namespace]
----
. Attendez que les conditions d'état de l'Astra indiquent que la mise à niveau est terminée et prête (`True`) :
+
[listing]
----
kubectl get AstraControlCenter -n [netapp-acc or custom namespace]
----
+
Réponse :

+
[listing]
----
NAME    UUID                                      VERSION     ADDRESS         READY
astra   9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f  22.11.0-24  10.111.111.111  True
----
+

NOTE: Pour surveiller le statut de la mise à niveau pendant l'opération, exécutez la commande suivante : `kubectl get AstraControlCenter -o yaml -n [netapp-acc or custom namespace]`

+

NOTE: Pour inspecter les journaux de l'opérateur de l'Astra Control Center, exécutez la commande suivante :
`kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f`





== Vérifiez l'état du système

. Connectez-vous à Astra Control Center.
. Vérifiez que la version a été mise à niveau. Consultez la page *support* de l'interface utilisateur.
. Vérifiez que tous vos clusters et applications gérés sont toujours présents et protégés.

