---
sidebar: sidebar 
permalink: use/view-dashboard.html 
keywords: dashboard, cluster health, unhealthy apps, protected apps, discovered apps 
summary: Sélectionnez Tableau de bord pour afficher une vue détaillée de vos applications, du calcul et de leur état de santé. 
---
= Affichez un récapitulatif de l'état des applications et du cluster
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Sélectionnez *Dashboard* pour afficher une vue de haut niveau de vos applications, clusters, systèmes back-end de stockage et leur état de santé.

Il ne s'agit pas seulement de numéros statiques ou d'États, mais vous pouvez explorer les données à partir de chacun d'entre eux. Par exemple, si les applications ne sont pas totalement protégées, vous pouvez passer le curseur de la souris sur l'icône pour identifier les applications qui ne sont pas totalement protégées, ce qui explique pourquoi.



== Mosaïque applications

La mosaïque *applications* vous aide à identifier les éléments suivants :

* Combien d'applications gérez-vous actuellement avec Astra ?
* Si ces applications gérées sont en bon état.
* Que les applications soient entièrement protégées (elles sont protégées si des sauvegardes récentes sont disponibles).
* Le nombre d'applications découvertes, mais non gérées.
+
Dans l'idéal, ce nombre est égal à zéro, car vous pouvez gérer ou ignorer les applications après leur découverte. Vous devez ensuite surveiller le nombre d'applications découvertes dans le tableau de bord pour déterminer quand les développeurs ajoutent de nouvelles applications à un cluster.





== Mosaïque de groupes

La mosaïque *clusters* fournit des détails similaires sur l'état de santé des clusters que vous gérez en utilisant Astra Control Center, et vous pouvez explorer vers le bas pour obtenir plus de détails comme vous pouvez avec une application.



== Mosaïque des systèmes back-end de stockage

La mosaïque *Storage backend* fournit des informations pour vous aider à identifier la santé des systèmes back-end :

* Nombre de systèmes back-end gérés
* Que ces systèmes back-end gérés soient en bon état
* Que les systèmes back-end soient entièrement protégés
* Le nombre de systèmes back-end découverts et ne sont pas encore gérés.

