---
sidebar: sidebar 
permalink: use/view-apps.html 
keywords: view app, view app status, view app protection status, view app pods, view persistent storage 
summary: 'Une fois que vous avez commencé à gérer une application, Astra Control fournit des informations détaillées sur l"application qui vous permet d"identifier son état, son état de protection, les pods, le stockage persistant, etc.' 
---
= Afficher l'état de santé et les détails d'une application
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Une fois que vous avez commencé à gérer une application, Astra Control fournit des informations détaillées sur l'application qui vous permet d'identifier son état de communication (si Astra Control peut communiquer avec l'application), son état de protection (qu'il soit entièrement protégé en cas de défaillance), les pods, le stockage persistant, etc.

.Étapes
. Dans l'interface utilisateur du Centre de contrôle Astra, sélectionnez *applications*, puis le nom d'une application.
. Vérifiez les informations.
+
Statut de l'application:: Fournit un état qui indique si Astra Control peut communiquer avec l'application.
+
--
** *App protection Status* : indique l'état de protection de l'application :
+
*** *Entièrement protégé* : l'application dispose d'un programme de sauvegarde actif et d'une sauvegarde réussie qui a moins d'une semaine
*** *Partiellement protégé* : l'application dispose d'un programme de sauvegarde actif, d'un programme de snapshots actif ou d'une sauvegarde ou d'un snapshot réussi
*** *Non protégé*: Les applications qui ne sont ni totalement protégées ni partiellement protégées.
+
_Vous ne pouvez pas être entièrement protégé tant que vous n'avez pas une sauvegarde récente_. Ceci est important, car les sauvegardes sont stockées dans un magasin d'objets à distance des volumes persistants. En cas de défaillance ou d'accident, le cluster doit être doté d'un stockage persistant, alors vous devez effectuer une sauvegarde pour effectuer une restauration. Un snapshot ne vous permettrait pas de restaurer votre système.



** *Présentation* : informations sur l'état des modules associés à l'application.
** *Protection des données* : permet de configurer une stratégie de protection des données et d'afficher les snapshots et sauvegardes existants.
** *Storage* : affiche les volumes persistants au niveau de l'application. L'état d'un volume persistant est du point de vue du cluster Kubernetes.
** *Ressources* : vous permet de vérifier quelles ressources sont sauvegardées et gérées.
** *Activité* : affiche les activités associées à l'application.
+

NOTE: Vous pouvez également afficher les informations de l'application à partir du Centre de contrôle Astra *Tableau de bord*. Dans l'onglet *applications* sous *Résumé des ressources*, vous pouvez sélectionner les applications gérées, qui vous permettent d'accéder à la page *applications*. Après avoir accédé à la page *applications*, suivez les étapes décrites ci-dessus.



--



