---
sidebar: sidebar 
permalink: get-started/cert-manager-prereqs.html 
keywords: astra control center, prereq, requirement, cert-manager, install 
summary: 'Si un cert-Manager existe déjà dans le cluster, vous devez effectuer certaines étapes préalables pour qu"Astra Control Center n"installe pas son propre cert-Manager.' 
---
= Configurez un cert-Manager externe
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Si un cert-Manager existe déjà dans votre cluster Kubernetes, vous devez effectuer certaines étapes préalables afin qu'Astra Control Center n'installe pas son propre cert-Manager.

.Étapes
. Vérifiez qu'un cert-Manager est installé :
+
[source, sh]
----
kubectl get pods -A | grep 'cert-manager'
----
+
Exemple de réponse :

+
[listing]
----
cert-manager   essential-cert-manager-84446f49d5-sf2zd              1/1     Running    0     6d5h
cert-manager   essential-cert-manager-cainjector-66dc99cc56-9ldmt   1/1     Running    0     6d5h
cert-manager   essential-cert-manager-webhook-56b76db9cc-fjqrq      1/1     Running    0     6d5h
----
. Créez une paire de certificats/clés pour le FQDN adresse :
+
[source, sh]
----
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt
----
+
Exemple de réponse :

+
[listing]
----
Generating a 2048 bit RSA private key
..................+++
........................................+++
writing new private key to 'tls.key'
----
. Créez un secret avec des fichiers générés précédemment :
+
[source, sh]
----
kubectl create secret tls selfsigned-tls --key tls.key --cert tls.crt -n <cert-manager-namespace>
----
+
Exemple de réponse :

+
[listing]
----
secret/selfsigned-tls created
----
. Créez un fichier ClusterIssuer qui est *exactement* ce qui suit mais qui comprend l'emplacement d'espace de noms où sont installés vos pods cert-Manager :
+
[source, yaml]
----
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: astra-ca-clusterissuer
  namespace: <cert-manager-namespace>
spec:
  ca:
    secretName: selfsigned-tls
----
+
[source, sh]
----
kubectl apply -f ClusterIssuer.yaml
----
+
Exemple de réponse :

+
[listing]
----
clusterissuer.cert-manager.io/astra-ca-clusterissuer created
----
. Vérifiez que l'émetteur de ClusterIssuer s'est correctement installé. `Ready` doit être de `True` avant de pouvoir continuer :
+
[source, sh]
----
kubectl get ClusterIssuer
----
+
Exemple de réponse :

+
[listing]
----
NAME                     READY   AGE
astra-ca-clusterissuer   True    9s
----
. Complétez le link:../get-started/install_acc.html["Procédure d'installation d'Astra Control Center"]. Il y a un link:../get-started/install_acc.html#configure-astra-control-center["Étape de configuration requise pour le groupe de centre de contrôle Astra YAML"] Dans lequel vous modifiez la valeur CRD pour indiquer que le cert-Manager est installé en externe. Vous devez effectuer cette étape au cours de l'installation pour que le centre de contrôle Astra reconnaisse le cert-Manager externe.

