---
sidebar: sidebar 
permalink: get-started/install_acc.html 
keywords: astra installation, install astra control center, how to install astra control, deploy, download from netapp support 
summary: 'Pour installer Astra Control Center après avoir défini certaines conditions préalables à l"environnement, téléchargez le pack et installez-le en suivant les étapes décrites.' 
---
= Installer le centre de contrôle Astra en suivant la procédure standard
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Pour installer Astra Control Center, téléchargez le bundle d'installation depuis le site de support NetApp et effectuez les opérations suivantes. Vous pouvez utiliser cette procédure pour installer Astra Control Center dans des environnements connectés à Internet ou équipés d'un filtre à air.

.Développez pour d'autres procédures d'installation
[%collapsible]
====
* *Installer avec Red Hat OpenShift OperatorHub* : utilisez cette option link:../get-started/acc_operatorhub_install.html["autre procédure"] Pour installer Astra Control Center sur OpenShift à l'aide d'OperatorHub.
* *Installer dans le Cloud public avec Cloud Volumes ONTAP backend*: Utiliser link:../get-started/install_acc-cvo.html["ces procédures"] Pour installer Astra Control Center dans Amazon Web Services (AWS), Google Cloud Platform (GCP) ou Microsoft Azure avec un système de stockage principal Cloud Volumes ONTAP.


====
Pour une démonstration du processus d'installation d'Astra Control Center, reportez-vous à la section https://www.youtube.com/watch?v=eurMV80b0Ks&list=PLdXI3bZJEw7mJz13z7YdiGCS6gNQgV_aN&index=5["vidéo"^].

.Avant de commencer
* *Respecter les conditions préalables environnementales* : link:requirements.html["Avant de commencer l'installation, préparez votre environnement pour le déploiement d'Astra Control Center"].
+

TIP: Déployez Astra Control Center dans un troisième domaine de panne ou sur un site secondaire. Cela est recommandé pour la réplication d'applications et la reprise sur incident transparente.



* *Assurer des services sains* : vérifier que tous les services API sont en bon état et disponibles :
+
[source, console]
----
kubectl get apiservices
----
* *Assurez-vous qu'un FQDN routable* : le FQDN Astra que vous prévoyez d'utiliser peut être routé vers le cluster. Cela signifie que vous avez une entrée DNS dans votre serveur DNS interne ou que vous utilisez une route URL de base déjà enregistrée.
* *Configurer cert Manager* : si un gestionnaire de certificats existe déjà dans le cluster, vous devez en effectuer quelques-uns link:../get-started/cert-manager-prereqs.html["étapes préalables"^] Pour qu'Astra Control Center ne tente pas d'installer son propre gestionnaire de certificat. Par défaut, Astra Control Center installe son propre gestionnaire de certificats lors de l'installation.
* *Accéder au registre d'images NetApp Astra Control* :
Vous avez la possibilité d'obtenir des images d'installation et des améliorations de fonctionnalités pour Astra Control, telles que Astra Control Provisioner, à partir du registre d'images NetApp.
+
.Développez pour les étapes
[%collapsible]
====
.. Notez l'ID de votre compte Astra Control dont vous aurez besoin pour vous connecter au registre.
+
Votre ID de compte s'affiche dans l'interface utilisateur web d'Astra Control Service. Sélectionnez l'icône de figure en haut à droite de la page, sélectionnez *API Access* et notez votre ID de compte.

.. A partir de la même page, sélectionnez *générer jeton API* et copiez la chaîne de jeton API dans le presse-papiers et enregistrez-la dans votre éditeur.
.. Connectez-vous au registre Astra Control :
+
[source, console]
----
docker login cr.astra.netapp.io -u <account-id> -p <api-token>
----


====
* *Considérons un maillage de service* : il est fortement recommandé de sécuriser les canaux de communication du cluster hôte Astra Control à l'aide d'un link:requirements.html#service-mesh-requirements["maillage de service pris en charge"^].
+
.Détails du maillage de service Istio
[%collapsible]
====
Pour l'utilisation du maillage de service Istio, vous devez effectuer les opérations suivantes :

** Ajouter un `istio-injection:enabled` <<Installation complète du centre de contrôle Astra et du conducteur,étiquette>> Dans l'espace de noms Astra avant de déployer Astra Control Center.
** Utilisez le `Generic` <<generic-ingress,paramètre d'entrée>> et fournissent une entrée alternative pour <<Configurer l'entrée pour l'équilibrage de charge,équilibrage de la charge externe>>.
** Pour les clusters Red Hat OpenShift, vous devez définir `NetworkAttachmentDefinition` Sur tous les espaces de noms Astra Control Center associés (`netapp-acc-operator`, `netapp-acc`, `netapp-monitoring` pour les clusters d'applications, ou tout espace de noms personnalisé ayant été substitué).
+
[listing]
----
cat <<EOF | oc -n netapp-acc-operator create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: istio-cni
EOF

cat <<EOF | oc -n netapp-acc create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: istio-cni
EOF

cat <<EOF | oc -n netapp-monitoring create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: istio-cni
EOF
----


====
* *Pilote SAN ONTAP uniquement* : si vous utilisez un pilote SAN ONTAP, assurez-vous que le multipath est activé sur tous vos clusters Kubernetes.


.Étapes
Pour installer le centre de contrôle Astra, procédez comme suit :

* <<Téléchargez et extrayez Astra Control Center>>
* <<Installez le plug-in NetApp Astra kubectl>>
* <<Ajoutez les images à votre registre local>>
* <<Configurez l'espace de noms et le secret pour les registres avec les exigences d'authentification>>
* <<Poser le conducteur du centre de commande Astra>>
* <<Configurer le centre de contrôle Astra>>
* <<Installation complète du centre de contrôle Astra et du conducteur>>
* <<Vérifiez l'état du système>>
* <<Configurer l'entrée pour l'équilibrage de charge>>
* <<Connectez-vous à l'interface utilisateur du centre de contrôle Astra>>



IMPORTANT: Ne supprimez pas l'opérateur du centre de contrôle Astra (par exemple, `kubectl delete -f astra_control_center_operator_deploy.yaml`) À tout moment pendant l'installation ou le fonctionnement d'Astra Control Center pour éviter de supprimer les modules.



== Téléchargez et extrayez Astra Control Center

Vous pouvez choisir de télécharger le bundle Astra Control Center depuis le site du support NetApp ou d'utiliser Docker pour extraire le bundle du registre d'images Astra Control Service.

[role="tabbed-block"]
====
.Site de support NetApp
--
. Téléchargez le pack contenant Astra Control Center (`astra-control-center-[version].tar.gz`) du https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["Page de téléchargements d'Astra Control Center"^].
. (Recommandé mais facultatif) Téléchargez le lot de certificats et de signatures pour Astra Control Center (`astra-control-center-certs-[version].tar.gz`) pour vérifier la signature du paquet.
+
.Développez pour plus d'informations
[%collapsible]
=====
[source, console]
----
tar -vxzf astra-control-center-certs-[version].tar.gz
----
[source, console]
----
openssl dgst -sha256 -verify certs/AstraControlCenter-public.pub -signature certs/astra-control-center-[version].tar.gz.sig astra-control-center-[version].tar.gz
----
La sortie s'affiche `Verified OK` une fois la vérification terminée.

=====
. Extraire les images du pack Astra Control Center :
+
[source, console]
----
tar -vxzf astra-control-center-[version].tar.gz
----


--
.Registre d'images Astra Control
--
. Connectez-vous à Astra Control Service.
. Sur le tableau de bord, sélectionnez *Deploy a autogéré instance d'Astra Control*.
. Suivez les instructions pour vous connecter au registre d'images Astra Control, extraire l'image d'installation d'Astra Control Center et extraire l'image.


--
====


== Installez le plug-in NetApp Astra kubectl

Vous pouvez utiliser le plug-in de ligne de commande NetApp Astra kubectl pour envoyer les images vers un référentiel Docker local.

.Avant de commencer
NetApp fournit des binaires de plug-ins pour différentes architectures CPU et systèmes d'exploitation. Avant d'effectuer cette tâche, vous devez savoir quelle unité centrale et quel système d'exploitation vous possédez.

Si vous avez déjà installé le plug-in à partir d'une installation précédente, link:../use/upgrade-acc.html#remove-the-netapp-astra-kubectl-plugin-and-install-it-again["vérifiez que vous disposez de la dernière version"^] avant d'effectuer ces étapes.

.Étapes
. Répertoriez les binaires kubectl du plug-in NetApp Astra disponibles :
+

NOTE: La bibliothèque de plug-ins kubectl fait partie du bundle tar et est extraite dans le dossier `kubectl-astra`.

+
[source, console]
----
ls kubectl-astra/
----
. Déplacez le fichier dont vous avez besoin pour votre système d'exploitation et votre architecture CPU dans le chemin actuel et renommez-le `kubectl-astra`:
+
[source, console]
----
cp kubectl-astra/<binary-name> /usr/local/bin/kubectl-astra
----




== Ajoutez les images à votre registre local

. Suivez la séquence d'étapes appropriée pour votre moteur de mise en conteneurs :


[role="tabbed-block"]
====
.Docker
--
. Accédez au répertoire racine du tarball. Vous devriez voir le `acc.manifest.bundle.yaml` et les répertoires suivants :
+
`acc/`
`kubectl-astra/`
`acc.manifest.bundle.yaml`

. Envoyez les images du package dans le répertoire d'images Astra Control Center vers votre registre local. Effectuez les remplacements suivants avant d'exécuter le `push-images` commande :
+
** Remplacez <BUNDLE_FILE> par le nom du fichier bundle Astra Control (`acc.manifest.bundle.yaml`).
** Remplacer <MY_FULL_REGISTRY_PATH> par l'URL du référentiel Docker, par exemple "https://<docker-registry>"[].
** Remplacez <MY_REGISTRY_USER> par le nom d'utilisateur.
** Remplacez <MY_REGISTRY_TOKEN> par un jeton autorisé pour le registre.
+
[source, console]
----
kubectl astra packages push-images -m <BUNDLE_FILE> -r <MY_FULL_REGISTRY_PATH> -u <MY_REGISTRY_USER> -p <MY_REGISTRY_TOKEN>
----




--
.Podman
--
. Accédez au répertoire racine du tarball. Vous devriez voir ce fichier et ce répertoire:
+
`acc/`
`kubectl-astra/`
`acc.manifest.bundle.yaml`

. Connectez-vous à votre registre :
+
[source, console]
----
podman login <YOUR_REGISTRY>
----
. Préparez et exécutez l'un des scripts suivants qui est personnalisé pour la version de Podman que vous utilisez. Remplacez <MY_FULL_REGISTRY_PATH> par l'URL de votre référentiel qui inclut tous les sous-répertoires.
+
[source, subs="specialcharacters,quotes"]
----
*Podman 4*
----
+
[source, console]
----
export REGISTRY=<MY_FULL_REGISTRY_PATH>
export PACKAGENAME=acc
export PACKAGEVERSION=23.10.0-68
export DIRECTORYNAME=acc
for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do
astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image: //')
astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')
podman tag ${astraImageNoPath} ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
podman push ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done
----
+
[source, subs="specialcharacters,quotes"]
----
*Podman 3*
----
+
[source, console]
----
export REGISTRY=<MY_FULL_REGISTRY_PATH>
export PACKAGENAME=acc
export PACKAGEVERSION=23.10.0-68
export DIRECTORYNAME=acc
for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do
astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image: //')
astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')
podman tag ${astraImageNoPath} ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
podman push ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done
----
+

NOTE: Le chemin d'accès à l'image que le script crée doit ressembler aux éléments suivants, selon la configuration de votre registre :

+
[listing]
----
https://downloads.example.io/docker-astra-control-prod/netapp/astra/acc/23.10.0-68/image:version
----


--
====


== Configurez l'espace de noms et le secret pour les registres avec les exigences d'authentification

. Exportez la configuration kubeconfig pour le cluster hôte Astra Control Center :
+
[source, console]
----
export KUBECONFIG=[file path]
----
+

IMPORTANT: Avant de terminer l'installation, assurez-vous que votre kubeconfig pointe vers le cluster où vous souhaitez installer Astra Control Center.

. Si vous utilisez un registre qui nécessite une authentification, vous devez procéder comme suit :
+
.Développez pour les étapes
[%collapsible]
====
.. Créer le `netapp-acc-operator` espace de noms :
+
[source, console]
----
kubectl create ns netapp-acc-operator
----
.. Créez un secret pour le `netapp-acc-operator` espace de noms. Ajoutez des informations sur Docker et exécutez la commande suivante :
+

NOTE: Le paramètre fictif `your_registry_path` doit correspondre à l'emplacement des images que vous avez téléchargées précédemment (par exemple, `[Registry_URL]/netapp/astra/astracc/23.10.0-68`).

+
[source, console]
----
kubectl create secret docker-registry astra-registry-cred -n netapp-acc-operator --docker-server=[your_registry_path] --docker-username=[username] --docker-password=[token]
----
+

NOTE: Si vous supprimez l'espace de noms après la génération du secret, recréez l'espace de noms, puis régénérez le secret pour l'espace de noms.

.. Créer le `netapp-acc` (ou espace de nom personnalisé).
+
[source, console]
----
kubectl create ns [netapp-acc or custom namespace]
----
.. Créez un secret pour le `netapp-acc` (ou espace de nom personnalisé). Ajoutez des informations sur Docker et exécutez la commande suivante :
+
[source, console]
----
kubectl create secret docker-registry astra-registry-cred -n [netapp-acc or custom namespace] --docker-server=[your_registry_path] --docker-username=[username] --docker-password=[token]
----


====




== Poser le conducteur du centre de commande Astra

. Modifier le répertoire :
+
[source, console]
----
cd manifests
----
. Modifiez le YAML de déploiement de l'opérateur Astra Control Center (`astra_control_center_operator_deploy.yaml`) pour faire référence à votre registre local et à votre secret.
+
[source, console]
----
vim astra_control_center_operator_deploy.yaml
----
+

NOTE: Un échantillon annoté YAML suit ces étapes.

+
.. Si vous utilisez un registre qui nécessite une authentification, remplacez la ligne par défaut de `imagePullSecrets: []` avec les éléments suivants :
+
[source, console]
----
imagePullSecrets: [{name: astra-registry-cred}]
----
.. Changer `ASTRA_IMAGE_REGISTRY` pour le `kube-rbac-proxy` image dans le chemin du registre où vous avez poussé les images dans un <<Ajoutez les images à votre registre local,étape précédente>>.
.. Changer `ASTRA_IMAGE_REGISTRY` pour le `acc-operator-controller-manager` image dans le chemin du registre où vous avez poussé les images dans un <<Ajoutez les images à votre registre local,étape précédente>>.


+
.Développez pour l'exemple astra_control_Center_Operator_Deploy.yaml
[%collapsible]
====
[listing, subs="+quotes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: ASTRA_IMAGE_REGISTRY/kube-rbac-proxy:v4.8.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        - name: ACCOP_HELM_INSTALLTIMEOUT
          value: 5m
        *image: ASTRA_IMAGE_REGISTRY/acc-operator:23.10.72*
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 750Mi
          requests:
            cpu: 100m
            memory: 75Mi
        securityContext:
          allowPrivilegeEscalation: false
      *imagePullSecrets: []*
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
----
====
. Poser le conducteur du centre de commande Astra :
+
[source, console]
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----
+
.Développer pour une réponse d'échantillon :
[%collapsible]
====
[listing]
----
namespace/netapp-acc-operator created
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io created
role.rbac.authorization.k8s.io/acc-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding created
configmap/acc-operator-manager-config created
service/acc-operator-controller-manager-metrics-service created
deployment.apps/acc-operator-controller-manager created
----
====
. Vérifiez que les pods sont en cours d'exécution :
+
[source, console]
----
kubectl get pods -n netapp-acc-operator
----




== Configurer le centre de contrôle Astra

. Modifiez le fichier de ressources personnalisées (CR) Astra Control Center (`astra_control_center.yaml`) pour créer des comptes, un support, un registre et d'autres configurations nécessaires :
+
[source, console]
----
vim astra_control_center.yaml
----
+

NOTE: Un échantillon annoté YAML suit ces étapes.

. Modifiez ou confirmez les paramètres suivants :
+
.<code> </code>
[%collapsible]
====
|===
| Réglage | Guidage | Type | Exemple 


| `accountName` | Modifiez le `accountName` Chaîne du nom que vous souhaitez associer au compte Astra Control Center. Il ne peut y avoir qu'un seul nom de compte. | chaîne | `Example` 
|===
====
+
.<code> </code>
[%collapsible]
====
|===
| Réglage | Guidage | Type | Exemple 


| `astraVersion` | La version d'Astra Control Center à déployer. Aucune action n'est nécessaire pour ce paramètre car la valeur sera pré-remplie. | chaîne | `23.10.0-68` 
|===
====
+
.<code> </code>
[%collapsible]
====
|===
| Réglage | Guidage | Type | Exemple 


| `astraAddress` | Modifiez le `astraAddress` Chaîne sur le FQDN (recommandé) ou l'adresse IP que vous souhaitez utiliser dans votre navigateur pour accéder à Astra Control Center. Cette adresse définit la façon dont Astra Control Center se trouve dans votre centre de données et est le même FQDN ou l'adresse IP que vous avez fournie à partir de votre équilibreur de charge une fois que vous avez terminé link:requirements.html["Exigences du centre de contrôle Astra"^]. REMARQUE : ne pas utiliser `http://` ou `https://` dans l'adresse. Copier ce FQDN pour l'utiliser dans un <<Connectez-vous à l'interface utilisateur du centre de contrôle Astra,plus tard>>. | chaîne | `astra.example.com` 
|===
====
+
.<code> </code>
[%collapsible]
====
Vos sélections dans cette section déterminent si vous allez participer à l'application de support proactif de NetApp, à NetApp Active IQ et à l'endroit où les données seront envoyées. Une connexion Internet est requise (port 442) et toutes les données de support sont anonymisées.

|===
| Réglage | Utiliser | Guidage | Type | Exemple 


| `autoSupport.enrolled` | Soit `enrolled` ou `url` les champs doivent être sélectionnés | Changer `enrolled` Pour AutoSupport à `false` pour les sites sans connexion internet ou sans conservation `true` pour les sites connectés. Un réglage de `true` Les données anonymes peuvent être envoyées à NetApp pour bénéficier d'un support. La sélection par défaut est `false` Aucune donnée de support n'est envoyée à NetApp. | Booléen | `false` (cette valeur est la valeur par défaut) 


| `autoSupport.url` | Soit `enrolled` ou `url` les champs doivent être sélectionnés | Cette URL détermine l'emplacement d'envoi des données anonymes. | chaîne | `https://support.netapp.com/asupprod/post/1.0/postAsup` 
|===
====
+
.<code> </code>
[%collapsible]
====
|===
| Réglage | Guidage | Type | Exemple 


| `email` | Modifiez le `email` chaîne à l'adresse d'administrateur initiale par défaut. Copiez cette adresse e-mail pour l'utiliser dans un <<Connectez-vous à l'interface utilisateur du centre de contrôle Astra,plus tard>>. Cette adresse e-mail sera utilisée comme nom d'utilisateur du compte initial pour se connecter à l'interface utilisateur et sera informée des événements dans Astra Control. | chaîne | `admin@example.com` 
|===
====
+
.<code> </code>
[%collapsible]
====
|===
| Réglage | Guidage | Type | Exemple 


| `firstName` | Prénom de l'administrateur initial par défaut associé au compte Astra. Le nom utilisé ici sera visible dans un en-tête de l'interface utilisateur après votre première connexion. | chaîne | `SRE` 
|===
====
+
.<code> </code>
[%collapsible]
====
|===
| Réglage | Guidage | Type | Exemple 


| `lastName` | Nom de l'administrateur initial par défaut associé au compte Astra. Le nom utilisé ici sera visible dans un en-tête de l'interface utilisateur après votre première connexion. | chaîne | `Admin` 
|===
====
+
.<code> de la gamme </code> de la gamme de produits
[%collapsible]
====
Vos sélections dans cette section définissent le registre d'images du conteneur qui héberge les images d'application Astra, l'opérateur du centre de contrôle Astra et le référentiel Helm d'Astra Control Center.

|===
| Réglage | Utiliser | Guidage | Type | Exemple 


| `imageRegistry.name` | Obligatoire | Nom du registre d'images dans lequel vous avez poussé les images dans le <<Poser le conducteur du centre de commande Astra,étape précédente>>. Ne pas utiliser `http://` ou `https://` dans le nom du registre. | chaîne | `example.registry.com/astra` 


| `imageRegistry.secret` | Obligatoire si la chaîne que vous avez entrée pour `imageRegistry.name' requires a secret.

IMPORTANT: If you are using a registry that does not require authorization, you must delete this `secret` ligne comprise entre `imageRegistry` sinon, l'installation échouera. | Nom du secret Kubernetes utilisé pour s'authentifier auprès du registre d'images. | chaîne | `astra-registry-cred` 
|===
====
+
.<code> </code>
[%collapsible]
====
|===
| Réglage | Guidage | Type | Exemple 


| `storageClass` | Modifiez le `storageClass` valeur à partir de `ontap-gold` À une autre ressource de classe de stockage Astra Trident, comme requis par votre installation. Lancer la commande `kubectl get sc` pour déterminer vos classes de stockage configurées existantes. L'une des classes de stockage basées sur Astra Trident doit être saisie dans le fichier manifeste (`astra-control-center-<version>.manifest`) Et sera utilisé pour ASTRA PVS. Si elle n'est pas définie, la classe de stockage par défaut sera utilisée. REMARQUE : si une classe de stockage par défaut est configurée, assurez-vous qu'elle est la seule classe de stockage à avoir l'annotation par défaut. | chaîne | `ontap-gold` 
|===
====
+
.Technologie <code>, </code>
[%collapsible]
====
|===
| Réglage | Guidage | Type | Options 


| `volumeReclaimPolicy` | Cette règle définit la règle de récupération pour les volumes persistants d'Astra. Définition de cette règle sur `Retain` Conserve les volumes persistants après la suppression d'Astra. Définition de cette règle sur `Delete` supprime les volumes persistants après la suppression d'astra. Si cette valeur n'est pas définie, les PV sont conservés. | chaîne  a| 
** `Retain` (Il s'agit de la valeur par défaut)
** `Delete`


|===
====
+
.<code> </code>
[#generic-ingress%collapsible]
====
|===
| Réglage | Guidage | Type | Options 


| `ingressType` | Utilisez l'un des types d'entrées suivants :

 `Generic`* (`ingressType: "Generic"`) (Par défaut)
Utilisez cette option si vous avez un autre contrôleur d'entrée en service ou si vous préférez utiliser votre propre contrôleur d'entrée. Après le déploiement du centre de contrôle Astra, vous devez configurer le link:../get-started/install_acc.html#set-up-ingress-for-load-balancing["contrôleur d'entrée"^] Pour exposer Astra Control Center avec une URL.

IMPORTANT : si vous avez l'intention d'utiliser un maillage de service avec Astra Control Center, vous devez sélectionner `Generic` comme type d'entrée et configurez votre propre link:../get-started/install_acc.html#set-up-ingress-for-load-balancing["contrôleur d'entrée"^].


*`AccTraefik`* (`ingressType: "AccTraefik"`)
Utilisez cette option lorsque vous préférez ne pas configurer de contrôleur d'entrée. Ceci déploie le centre de contrôle Astra `traefik` Passerelle en tant que service de type Kubernetes LoadBalancer.

Le centre de contrôle Astra utilise un service de type « équilibreur de charge » (`svc/traefik` Dans l'espace de noms du centre de contrôle Astra), et exige qu'il se voit attribuer une adresse IP externe accessible. Si des équilibreurs de charge sont autorisés dans votre environnement et que vous n'en avez pas encore configuré, vous pouvez utiliser MetalLB ou un autre équilibreur de charge de service externe pour attribuer une adresse IP externe au service. Dans la configuration du serveur DNS interne, pointez le nom DNS choisi pour Astra Control Center vers l'adresse IP à équilibrage de charge.

REMARQUE : pour plus de détails sur le type de service « LoadBalancer » et Ingress, reportez-vous à la section link:../get-started/requirements.html["De formation"^]. | chaîne  a| 
** `Generic` (il s'agit de la valeur par défaut)
** `AccTraefik`


|===
====
+
.<code>scaleSize</code>
[%collapsible]
====
|===
| Réglage | Guidage | Type | Options 


| `scaleSize` | Par défaut, Astra utilisera la haute disponibilité (HA) `scaleSize` de `Medium`, Qui déploie la plupart des services en haute disponibilité et déploie plusieurs répliques pour assurer la redondance. Avec `scaleSize` comme `Small`, Astra réduira le nombre de répliques pour tous les services, à l'exception des services essentiels, afin de réduire la consommation. CONSEIL : `Medium` les déploiements se composent d'environ 100 pods (à l'exclusion des workloads transitoires). 100 modules sont basés sur une configuration à trois nœuds maîtres et trois nœuds workers). Tenez compte des contraintes de limite réseau par pod qui peuvent représenter un problème dans votre environnement, en particulier lors de l'examen des scénarios de reprise d'activité. | chaîne  a| 
** `Small`
** `Medium` (Il s'agit de la valeur par défaut)


|===
====
+
.<code> </code>
[%collapsible]
====
|===
| Réglage | Guidage | Type | Options 


| `astraResourcesScaler` | Options d'évolutivité pour les limites de ressources AstrakControlCenter. Par défaut, Astra Control Center se déploie avec des demandes de ressources définies pour la plupart des composants d'Astra. Avec cette configuration, la pile logicielle Astra Control Center est plus performante dans les environnements soumis à une charge et à une évolutivité accrues des applications. Cependant, dans les scénarios utilisant des grappes de développement ou de test plus petites, le champ CR `astraResourcesScalar` peut être réglé sur `Off`. Cela désactive les demandes de ressources et permet un déploiement sur les clusters plus petits. | chaîne  a| 
** `Default` (Il s'agit de la valeur par défaut)
** `Off`


|===
====
+
.<code>additionalValues</code>
[%collapsible]
====

IMPORTANT: Ajoutez les valeurs supplémentaires suivantes à l'Astra Control Center CR pour éviter un problème connu lors de l'installation :

[listing]
----
additionalValues:
    keycloak-operator:
      livenessProbe:
        initialDelaySeconds: 180
      readinessProbe:
        initialDelaySeconds: 180
----
** Pour les communications Astral Control Center et Cloud Insights, la vérification du certificat TLS est désactivée par défaut. Vous pouvez activer la vérification de certification TLS pour la communication entre Cloud Insights et le cluster hôte Astra Control Center et le cluster géré en ajoutant la section suivante à la `additionalValues`.


[listing]
----
  additionalValues:
    netapp-monitoring-operator:
      config:
        ciSkipTlsVerify: false
    cloud-insights-service:
      config:
        ciSkipTlsVerify: false
    telemetry-service:
      config:
        ciSkipTlsVerify: false
----
====
+
.<code> </code>
[%collapsible]
====
Vos sélections dans cette section déterminent comment Astra Control Center doit traiter les CRD.

|===
| Réglage | Guidage | Type | Exemple 


| `crds.externalCertManager` | Si vous utilisez un gestionnaire de certificats externe, modifiez-le `externalCertManager` à `true`. La valeur par défaut `false` Provoque l'installation d'Astra Control Center de ses propres CRD de cert Manager lors de l'installation. Les CRDS sont des objets à l'échelle du cluster et leur installation peut avoir un impact sur d'autres parties du cluster. Vous pouvez utiliser cet indicateur pour signaler à Astra Control Center que ces CRD seront installés et gérés par l'administrateur de cluster en dehors du centre de contrôle Astra. | Booléen | `False` (cette valeur est la valeur par défaut) 


| `crds.externalTraefik` | Par défaut, Astra Control Center installe les CRD Traefik requis. Les CRDS sont des objets à l'échelle du cluster et leur installation peut avoir un impact sur d'autres parties du cluster. Vous pouvez utiliser cet indicateur pour signaler à Astra Control Center que ces CRD seront installés et gérés par l'administrateur de cluster en dehors du centre de contrôle Astra. | Booléen | `False` (cette valeur est la valeur par défaut) 
|===
====



IMPORTANT: Assurez-vous d'avoir sélectionné la classe de stockage et le type d'entrée appropriés pour votre configuration avant de terminer l'installation.

.Développez pour l'exemple astra_control_Center.yaml
[%collapsible]
====
[listing, subs="+quotes"]
----
apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra
spec:
  accountName: "Example"
  astraVersion: "ASTRA_VERSION"
  astraAddress: "astra.example.com"
  autoSupport:
    enrolled: true
  email: "[admin@example.com]"
  firstName: "SRE"
  lastName: "Admin"
  imageRegistry:
    name: "[your_registry_path]"
    secret: "astra-registry-cred"
  storageClass: "ontap-gold"
  volumeReclaimPolicy: "Retain"
  ingressType: "Generic"
  scaleSize: "Medium"
  astraResourcesScaler: "Default"
  additionalValues:
    keycloak-operator:
      livenessProbe:
        initialDelaySeconds: 180
      readinessProbe:
        initialDelaySeconds: 180
  crds:
    externalTraefik: false
    externalCertManager: false
----
====


== Installation complète du centre de contrôle Astra et du conducteur

. Si vous ne l'avez pas déjà fait dans une étape précédente, créez le `netapp-acc` (ou personnalisée) espace de noms :
+
[source, console]
----
kubectl create ns [netapp-acc or custom namespace]
----
. Si vous utilisez un maillage de service avec Astra Control Center, ajoutez l'étiquette suivante au `netapp-acc` ou un espace de noms personnalisé :
+

IMPORTANT: Votre type d'entrée (`ingressType`) doit être défini sur `Generic` Dans Astra Control Center CR avant de passer à cette commande.

+
[source, console]
----
kubectl label ns [netapp-acc or custom namespace] istio-injection:enabled
----
. (Recommandé) https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/["Activez les licences MTL strictes"^] Pour le maillage de service Istio :
+
[source, console]
----
kubectl apply -n istio-system -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
EOF
----
. Poser le centre de contrôle Astra dans le `netapp-acc` (ou votre espace de noms personnalisé) :
+
[source, console]
----
kubectl apply -f astra_control_center.yaml -n [netapp-acc or custom namespace]
----



IMPORTANT: L'opérateur d'Astra Control Center effectue une vérification automatique des exigences de l'environnement. Manquant link:../get-started/requirements.html["de formation"^] Peut entraîner une défaillance de votre installation ou un dysfonctionnement d'Astra Control Center. Voir la <<Vérifiez l'état du système,section suivante>> pour vérifier la présence de messages d'avertissement liés au contrôle automatique du système.



== Vérifiez l'état du système

Vous pouvez vérifier l'état du système à l'aide des commandes kubectl. Si vous préférez utiliser OpenShift, vous pouvez utiliser des commandes oc comparables pour les étapes de vérification.

.Étapes
. Vérifiez que le processus d'installation n'a pas produit de messages d'avertissement relatifs aux vérifications de validation :
+
[source, console]
----
kubectl get acc [astra or custom Astra Control Center CR name] -n [netapp-acc or custom namespace] -o yaml
----
+

NOTE: Des messages d'avertissement supplémentaires sont également signalés dans les journaux de l'opérateur d'Astra Control Center.

. Corrigez tous les problèmes de votre environnement qui ont été signalés par les vérifications automatisées des exigences.
+

NOTE: Vous pouvez corriger les problèmes en vous assurant que votre environnement respecte les link:../get-started/requirements.html["de formation"^] Pour Astra Control Center.

. Vérifiez que tous les composants du système sont correctement installés.
+
[source, console]
----
kubectl get pods -n [netapp-acc or custom namespace]
----
+
Chaque pod doit avoir un statut de `Running`. Le déploiement des modules du système peut prendre plusieurs minutes.

+
.Développez pour obtenir une réponse d'échantillon
[%collapsible]
====
[listing, subs="+quotes"]
----
NAME                                          READY   STATUS      RESTARTS     AGE
acc-helm-repo-6cc7696d8f-pmhm8                1/1     Running     0            9h
activity-597fb656dc-5rd4l                     1/1     Running     0            9h
activity-597fb656dc-mqmcw                     1/1     Running     0            9h
api-token-authentication-62f84                1/1     Running     0            9h
api-token-authentication-68nlf                1/1     Running     0            9h
api-token-authentication-ztgrm                1/1     Running     0            9h
asup-669d4ddbc4-fnmwp                         1/1     Running     1 (9h ago)   9h
authentication-78789d7549-lk686               1/1     Running     0            9h
bucketservice-65c7d95496-24x7l                1/1     Running     3 (9h ago)   9h
cert-manager-c9f9fbf9f-k8zq2                  1/1     Running     0            9h
cert-manager-c9f9fbf9f-qjlzm                  1/1     Running     0            9h
cert-manager-cainjector-dbbbd8447-b5qll       1/1     Running     0            9h
cert-manager-cainjector-dbbbd8447-p5whs       1/1     Running     0            9h
cert-manager-webhook-6f97bb7d84-4722b         1/1     Running     0            9h
cert-manager-webhook-6f97bb7d84-86kv5         1/1     Running     0            9h
certificates-59d9f6f4bd-2j899                 1/1     Running     0            9h
certificates-59d9f6f4bd-9d9k6                 1/1     Running     0            9h
certificates-expiry-check-28011180--1-8lkxz   0/1     Completed   0            9h
cloud-extension-5c9c9958f8-jdhrp              1/1     Running     0            9h
cloud-insights-service-5cdd5f7f-pp8r5         1/1     Running     0            9h
composite-compute-66585789f4-hxn5w            1/1     Running     0            9h
composite-volume-68649f68fd-tb7p4             1/1     Running     0            9h
credentials-dfc844c57-jsx92                   1/1     Running     0            9h
credentials-dfc844c57-xw26s                   1/1     Running     0            9h
entitlement-7b47769b87-4jb6c                  1/1     Running     0            9h
features-854d8444cc-c24b7                     1/1     Running     0            9h
features-854d8444cc-dv6sm                     1/1     Running     0            9h
fluent-bit-ds-9tlv4                           1/1     Running     0            9h
fluent-bit-ds-bpkcb                           1/1     Running     0            9h
fluent-bit-ds-cxmwx                           1/1     Running     0            9h
fluent-bit-ds-jgnhc                           1/1     Running     0            9h
fluent-bit-ds-vtr6k                           1/1     Running     0            9h
fluent-bit-ds-vxqd5                           1/1     Running     0            9h
graphql-server-7d4b9d44d5-zdbf5               1/1     Running     0            9h
identity-6655c48769-4pwk8                     1/1     Running     0            9h
influxdb2-0                                   1/1     Running     0            9h
keycloak-operator-55479d6fc6-slvmt            1/1     Running     0            9h
krakend-f487cb465-78679                       1/1     Running     0            9h
krakend-f487cb465-rjsxx                       1/1     Running     0            9h
license-64cbc7cd9c-qxsr8                      1/1     Running     0            9h
login-ui-5db89b5589-ndb96                     1/1     Running     0            9h
loki-0                                        1/1     Running     0            9h
metrics-facade-8446f64c94-x8h7b               1/1     Running     0            9h
monitoring-operator-6b44586965-pvcl4          2/2     Running     0            9h
nats-0                                        1/1     Running     0            9h
nats-1                                        1/1     Running     0            9h
nats-2                                        1/1     Running     0            9h
nautilus-85754d87d7-756qb                     1/1     Running     0            9h
nautilus-85754d87d7-q8j7d                     1/1     Running     0            9h
openapi-5f9cc76544-7fnjm                      1/1     Running     0            9h
openapi-5f9cc76544-vzr7b                      1/1     Running     0            9h
packages-5db49f8b5-lrzhd                      1/1     Running     0            9h
polaris-consul-consul-server-0                1/1     Running     0            9h
polaris-consul-consul-server-1                1/1     Running     0            9h
polaris-consul-consul-server-2                1/1     Running     0            9h
polaris-keycloak-0                            1/1     Running     2 (9h ago)   9h
polaris-keycloak-1                            1/1     Running     0            9h
polaris-keycloak-2                            1/1     Running     0            9h
polaris-keycloak-db-0                         1/1     Running     0            9h
polaris-keycloak-db-1                         1/1     Running     0            9h
polaris-keycloak-db-2                         1/1     Running     0            9h
polaris-mongodb-0                             1/1     Running     0            9h
polaris-mongodb-1                             1/1     Running     0            9h
polaris-mongodb-2                             1/1     Running     0            9h
polaris-ui-66fb99479-qp9gq                    1/1     Running     0            9h
polaris-vault-0                               1/1     Running     0            9h
polaris-vault-1                               1/1     Running     0            9h
polaris-vault-2                               1/1     Running     0            9h
public-metrics-76fbf9594d-zmxzw               1/1     Running     0            9h
storage-backend-metrics-7d7fbc9cb9-lmd25      1/1     Running     0            9h
storage-provider-5bdd456c4b-2fftc             1/1     Running     0            9h
task-service-87575df85-dnn2q                  1/1     Running     3 (9h ago)   9h
task-service-task-purge-28011720--1-q6w4r     0/1     Completed   0            28m
task-service-task-purge-28011735--1-vk6pd     1/1     Running     0            13m
telegraf-ds-2r2kw                             1/1     Running     0            9h
telegraf-ds-6s9d5                             1/1     Running     0            9h
telegraf-ds-96jl7                             1/1     Running     0            9h
telegraf-ds-hbp84                             1/1     Running     0            9h
telegraf-ds-plwzv                             1/1     Running     0            9h
telegraf-ds-sr22c                             1/1     Running     0            9h
telegraf-rs-4sbg8                             1/1     Running     0            9h
telemetry-service-fb9559f7b-mk9l7             1/1     Running     3 (9h ago)   9h
tenancy-559bbc6b48-5msgg                      1/1     Running     0            9h
traefik-d997b8877-7xpf4                       1/1     Running     0            9h
traefik-d997b8877-9xv96                       1/1     Running     0            9h
trident-svc-585c97548c-d25z5                  1/1     Running     0            9h
vault-controller-88484b454-2d6sr              1/1     Running     0            9h
vault-controller-88484b454-fc5cz              1/1     Running     0            9h
vault-controller-88484b454-jktld              1/1     Running     0            9h
----
====
. (En option) regarder le `acc-operator` journaux de suivi de la progression :
+
[source, console]
----
kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f
----
+

NOTE: `accHost` l'enregistrement du cluster est l'une des dernières opérations. en cas de défaillance, le déploiement ne pourra pas échouer. Dans l'éventualité où un échec d'enregistrement du cluster était indiqué dans les journaux, vous pouvez essayer de nouveau l'enregistrement via le link:../get-started/setup_overview.html#add-cluster["Ajout du flux de travail du cluster dans l'interface utilisateur"^] Ou API.

. Lorsque tous les modules sont en cours d'exécution, vérifiez que l'installation a réussi (`READY` est `True`) Et obtenez le mot de passe de configuration initial que vous utiliserez lorsque vous vous connectez à Astra Control Center :
+
[source, console]
----
kubectl get AstraControlCenter -n [netapp-acc or custom namespace]
----
+
Réponse :

+
[listing]
----
NAME    UUID                                  VERSION     ADDRESS         READY
astra   9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f  23.10.0-68   10.111.111.111  True
----
+

IMPORTANT: Copiez la valeur UUID. Le mot de passe est `ACC-` Suivi de la valeur UUID (`ACC-[UUID]` ou, dans cet exemple, `ACC-9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f`).





== Configurer l'entrée pour l'équilibrage de charge

Vous pouvez configurer un contrôleur d'entrée Kubernetes qui gère l'accès externe aux services. Ces procédures fournissent des exemples de configuration pour un contrôleur d'entrée si vous avez utilisé la valeur par défaut de `ingressType: "Generic"` Dans la ressource personnalisée Astra Control Center (`astra_control_center.yaml`). Vous n'avez pas besoin d'utiliser cette procédure si vous avez spécifié `ingressType: "AccTraefik"` Dans la ressource personnalisée Astra Control Center (`astra_control_center.yaml`).

Après le déploiement du centre de contrôle Astra, vous devrez configurer le contrôleur d'entrée pour exposer le centre de contrôle Astra à une URL.

Les étapes de configuration varient en fonction du type de contrôleur d'entrée utilisé. Le centre de contrôle Astra prend en charge de nombreux types de contrôleurs d'entrée. Ces procédures de configuration fournissent des exemples d'étapes pour certains types de contrôleurs d'entrée courants.

.Avant de commencer
* Le requis https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/["contrôleur d'entrée"] doit déjà être déployé.
* Le https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class["classe d'entrée"] correspondant au contrôleur d'entrée doit déjà être créé.


.Étapes pour l'entrée Istio
[%collapsible]
====
. Configurer l'entrée Istio.
+

NOTE: Cette procédure suppose que Istio est déployé à l'aide du profil de configuration par défaut.

. Rassemblez ou créez le certificat et le fichier de clé privée souhaités pour la passerelle d'entrée.
+
Vous pouvez utiliser un certificat signé par une autorité de certification ou auto-signé. Le nom commun doit être l'adresse Astra (FQDN).

+
Exemple de commande :

+
[source, console]
----
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt
----
. Créez un secret `tls secret name` de type `kubernetes.io/tls` Pour une clé privée TLS et un certificat dans `istio-system namespace` Comme décrit dans les secrets TLS.
+
Exemple de commande :

+
[source, console]
----
kubectl create secret tls [tls secret name] --key="tls.key" --cert="tls.crt" -n istio-system
----
+

TIP: Le nom du secret doit correspondre au `spec.tls.secretName` fourni dans `istio-ingress.yaml` fichier.

. Déployer une ressource d'entrée dans le `netapp-acc` (ou nom personnalisé) de l'espace de noms utilisant le type de ressource v1 pour un schéma (`istio-Ingress.yaml` est utilisé dans cet exemple) :
+
[listing]
----
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: [netapp-acc or custom namespace]
spec:
  ingressClassName: istio
  tls:
  - hosts:
    - <ACC address>
    secretName: [tls secret name]
  rules:
  - host: [ACC address]
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik
            port:
              number: 80
----
. Appliquer les modifications :
+
[source, console]
----
kubectl apply -f istio-Ingress.yaml
----
. Vérifier l'état de l'entrée :
+
[source, console]
----
kubectl get ingress -n [netapp-acc or custom namespace]
----
+
Réponse :

+
[listing]
----
NAME    CLASS HOSTS             ADDRESS         PORTS   AGE
ingress istio astra.example.com 172.16.103.248  80, 443 1h
----
. <<Configurer le centre de contrôle Astra,Terminer l'installation du centre de contrôle Astra>>.


====
.Étapes du contrôleur d'entrée Nginx
[%collapsible]
====
. Créer un secret de type `kubernetes.io/tls` Pour une clé privée TLS et un certificat dans `netapp-acc` (ou espace de noms personnalisé) comme décrit dans https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets["Secrets TLS"].
. Déployez une ressource entrée dans `netapp-acc` (ou nom personnalisé) de l'espace de noms utilisant le type de ressource v1 pour un schéma (`nginx-Ingress.yaml` est utilisé dans cet exemple) :
+
[source, yaml]
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netapp-acc-ingress
  namespace: [netapp-acc or custom namespace]
spec:
  ingressClassName: [class name for nginx controller]
  tls:
  - hosts:
    - <ACC address>
    secretName: [tls secret name]
  rules:
  - host: <ACC address>
    http:
      paths:
        - path:
          backend:
            service:
              name: traefik
              port:
                number: 80
          pathType: ImplementationSpecific
----
. Appliquer les modifications :
+
[source, console]
----
kubectl apply -f nginx-Ingress.yaml
----



WARNING: NetApp recommande d'installer le contrôleur nginx en tant que déploiement plutôt qu'en tant que `daemonSet`.

====
.Étapes du contrôleur d'entrée OpenShift
[%collapsible]
====
. Procurez-vous votre certificat et obtenez les fichiers de clé, de certificat et d'autorité de certification prêts à l'emploi par la route OpenShift.
. Création de la route OpenShift :
+
[source, console]
----
oc create route edge --service=traefik --port=web -n [netapp-acc or custom namespace] --insecure-policy=Redirect --hostname=<ACC address> --cert=cert.pem --key=key.pem
----


====


== Connectez-vous à l'interface utilisateur du centre de contrôle Astra

Après avoir installé Astra Control Center, vous modifierez le mot de passe de l'administrateur par défaut et vous connecterez au tableau de bord de l'interface utilisateur de Astra Control Center.

.Étapes
. Dans un navigateur, saisissez le nom de domaine complet (y compris le `https://` prefix) que vous avez utilisé dans `astraAddress` dans le `astra_control_center.yaml` CR quand <<Configurer le centre de contrôle Astra,Vous avez installé Astra Control Center>>.
. Acceptez les certificats auto-signés si vous y êtes invité.
+

NOTE: Vous pouvez créer un certificat personnalisé après la connexion.

. Dans la page de connexion à Astra Control Center, entrez la valeur que vous avez utilisée `email` dans `astra_control_center.yaml` CR quand <<Configurer le centre de contrôle Astra,Vous avez installé Astra Control Center>>, suivi du mot de passe de configuration initiale (`ACC-[UUID]`).
+

NOTE: Si vous saisissez trois fois un mot de passe incorrect, le compte admin est verrouillé pendant 15 minutes.

. Sélectionnez *connexion*.
. Modifiez le mot de passe lorsque vous y êtes invité.
+

NOTE: S'il s'agit de votre première connexion et que vous oubliez le mot de passe et qu'aucun autre compte d'utilisateur administratif n'a encore été créé, contactez https://mysupport.netapp.com/site/["Support NetApp"] pour obtenir de l'aide sur la récupération des mots de

. (Facultatif) supprimez le certificat TLS auto-signé existant et remplacez-le par un link:../get-started/configure-after-install.html#add-a-custom-tls-certificate["Certificat TLS personnalisé signé par une autorité de certification"^].




== Dépanner l'installation

Si l'un des services est dans `Error` état, vous pouvez inspecter les journaux. Rechercher les codes de réponse API dans la plage 400 à 500. Ceux-ci indiquent l'endroit où un échec s'est produit.

.Options
* Pour inspecter les journaux de l'opérateur de l'Astra Control Center, entrez ce qui suit :
+
[source, console]
----
kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f
----
* Pour vérifier la sortie de l'Astra Control Center CR :
+
[listing]
----
kubectl get acc -n [netapp-acc or custom namespace] -o yaml
----




== Et la suite

* (Facultatif) en fonction de votre environnement, effectuez l'installation complète après l'installation link:configure-after-install.html["étapes de configuration"].
* Terminez le déploiement en effectuant le processus link:setup_overview.html["tâches de configuration"].

