---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: what are astra kubernetes requirements, astra control requirements, astra supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking, environment, operational, operational environment, hosting, host, cluster, clusters, tanzu, tkg, tkgi, grid, kubernetes, k8s 
summary: Commencez à utiliser Astra Control Center en vérifiant la prise en charge de vos clusters Kubernetes, de vos applications et de votre navigateur Web. 
---
= Exigences du centre de contrôle Astra
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Commencez par vérifier que votre environnement opérationnel, vos clusters d'applications, vos applications, vos licences et votre navigateur Web sont prêts. Assurez-vous que votre environnement répond à ces exigences pour déployer et exploiter Astra Control Center.



== Environnements Kubernetes de cluster hôte pris en charge

ASTRA Control Center a été validé avec les environnements hôtes Kubernetes suivants :


NOTE: Assurez-vous que l'environnement Kubernetes que vous choisissez d'héberger Astra Control Center répond aux exigences de ressources de base indiquées dans la documentation officielle de l'environnement.

|===
| Distribution Kubernetes sur le cluster hôte | Versions prises en charge 


| Azure Kubernetes Service sur Azure Stack HCI | Pile Azure HCI 21H2 et 22H2 avec AKS 1.24.x et 1.25.x 


| Anthos de Google | 1.15 à 1.16 (voir <<Exigences d'entrée de Google Anthos>>) 


| Kubernetes (en amont) | 1.26 à 1.28 


| Rancher Kubernetes Engine (RKE) | RKE 1.3 avec Rancher Manager 2.6
RKE 1.4 avec Rancher Manager 2.7
RKE 2 (v1.24.x) avec Rancher 2.6
RKE 2 (v1.26.x) avec Rancher 2.7 


| Plateforme de conteneurs Red Hat OpenShift | 4.11 à 4.14 


| VMware Tanzu Kubernetes Grid Integrated Edition | 1.16.x (voir <<Ressources requises pour le cluster hôte>>) 
|===


== Ressources requises pour le cluster hôte

Outre les exigences de l'environnement en matière de ressources, Astra Control Center requiert les ressources suivantes :


NOTE: De telles exigences supposent que Astra Control Center est la seule application qui s'exécute dans l'environnement opérationnel. Si l'environnement exécute des applications supplémentaires, ajustez ces exigences minimales en conséquence.

* *Extensions CPU* : les CPU de tous les noeuds de l'environnement d'hébergement doivent avoir des extensions AVX activées.
* *Nœuds de travail* : au moins 3 nœuds de travail au total, avec 4 cœurs de processeur et 12 Go de RAM chacun
* *Configuration requise pour le cluster VMware Tanzu Kubernetes Grid* : lors de l'hébergement d'Astra Control Center sur un cluster VMware Tanzu Kubernetes Grid (TKG) ou Tanzu Kubernetes Grid Integrated Edition (TKGi), tenez compte des points suivants.
+
** Le token de fichier de configuration VMware TKG et TKGi par défaut expire dix heures après le déploiement. Si vous utilisez des produits de la gamme Tanzu, vous devez générer un fichier de configuration de cluster Kubernetes Tanzu avec un jeton non expirant pour éviter les problèmes de connexion entre Astra Control Center et les clusters d'applications gérés. Pour obtenir des instructions, rendez-vous sur https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.2/nsx-application-platform/GUID-52A52C0B-9575-43B6-ADE2-E8640E22C29F.html["Documentation produit relative au data Center VMware NSX-T"^]
** Utilisez le `kubectl get nsxlbmonitors -A` commande pour voir si un moniteur de service est déjà configuré pour accepter le trafic d'entrée. S'il en existe un, vous ne devez pas installer MetalLB, car le moniteur de service existant remplacera toute nouvelle configuration d'équilibreur de charge.
** Désactivez la mise en œuvre par défaut des classes de stockage TKG ou TKGi sur les clusters d'applications devant être gérés par Astra Control. Vous pouvez le faire en modifiant le `TanzuKubernetesCluster` ressource sur le cluster d'espace de noms.
** Tenez compte des exigences spécifiques de l'Astra Trident lorsque vous déployez le centre de contrôle Astra dans un environnement TKG ou TKGi. Pour plus d'informations, reportez-vous à la section https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html#other-known-configuration-options["Documentation Astra Trident"^].






== Exigences de maillage de service

Il est fortement recommandé d'installer une version vanille prise en charge du maillage de service Istio sur le cluster hôte Astra Control Center. Reportez-vous à la section https://istio.io/latest/docs/releases/supported-releases/["versions prises en charge"^] Pour les versions prises en charge d'Istio. Les versions de marque du maillage de services Istio, telles qu'OpenShift Service mesh, ne sont pas validées avec Astra Control Center.

Pour intégrer Astra Control Center avec le maillage de service Istio installé sur le cluster hôte, vous devez effectuer l'intégration dans le cadre d'Astra Control Center link:../get-started/install_acc.html["installation"] et non indépendant de ce processus.


NOTE: L'installation d'Astra Control Service sans configurer de maillage de services sur le cluster hôte peut avoir de graves implications en matière de sécurité.



== Exigences d'Astra Trident

Assurez-vous de répondre aux exigences Astra Trident suivantes, spécifiques aux besoins de votre environnement :

* *Version minimale pour une utilisation avec Astra Control Center* : Astra Trident 23.01 ou version ultérieure installée et configurée
* *Configuration ONTAP avec Astra Trident* :
+
** *Classe de stockage* : configurez au moins une classe de stockage Astra Trident sur le cluster. Si une classe de stockage par défaut est configurée, assurez-vous qu'elle est la seule classe de stockage avec la désignation par défaut.
** *Pilotes de stockage et nœuds worker* : Assurez-vous de configurer les nœuds worker de votre cluster avec les pilotes de stockage appropriés afin que les pods puissent interagir avec le stockage back-end. Le centre de contrôle Astra prend en charge les pilotes ONTAP suivants fournis par Astra Trident :
+
*** `ontap-nas`
*** `ontap-san`
*** `ontap-san-economy` (la réplication d'application n'est pas disponible avec ce type de classe de stockage)
*** `ontap-nas-economy` (les snapshots, les règles de réplication et les règles de protection ne sont pas disponibles avec ce type de classe de stockage)








== De provisionnement Astra Control

Pour utiliser la fonctionnalité de stockage avancée Astra Control Provisioner, vous devez installer Astra Trident 23.10 ou version ultérieure et activer link:../use/enable-acp.html["Fonctionnalité Astra Control Provisioner"].



== Systèmes back-end

Assurez-vous que vous disposez d'un back-end pris en charge avec une capacité suffisante.

* *Capacité de stockage requise* : au moins 500 Go disponibles
* *Systèmes back-end pris en charge* : Astra Control Center prend en charge les systèmes back-end de stockage suivants :
+
** NetApp ONTAP 9.9.1 ou version ultérieure des systèmes AFF, FAS et ASA
** NetApp ONTAP Select 9.9.1 ou version ultérieure
** NetApp Cloud Volumes ONTAP 9.9.1 ou version ultérieure
** Longhorn 1.5.0 ou version ultérieure
+
*** Nécessite la création manuelle d'un objet VolumeSnapshotClass. Reportez-vous à la https://longhorn.io/docs/1.5.0/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-snapshot/#create-a-csi-volumesnapshot-associated-with-longhorn-snapshot["Documentation Longhorn"^] pour obtenir des instructions.


** NetApp MetroCluster
+
*** Les clusters Kubernetes gérés doivent se trouver dans une configuration étendue.


** Systèmes back-end de stockage disponibles avec les fournisseurs cloud pris en charge






=== Licences ONTAP

Pour utiliser Astra Control Center, vérifiez que vous disposez des licences ONTAP suivantes, en fonction de ce que vous devez accomplir :

* FlexClone
* SnapMirror : en option. Elle est nécessaire uniquement pour la réplication vers des systèmes distants à l'aide de la technologie SnapMirror. Reportez-vous à la section https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["Informations sur la licence SnapMirror"^].
* Licence S3 : en option. Nécessaire uniquement pour les compartiments ONTAP S3


Pour vérifier si votre système ONTAP dispose des licences requises, reportez-vous à la section https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["Gérer les licences ONTAP"^].



=== NetApp MetroCluster

Lorsque vous utilisez NetApp MetroCluster comme système back-end de stockage, vous devez effectuer les opérations suivantes :

* Spécifier une LIF de gestion de SVM en tant qu'option back-end dans le pilote Astra Trident que vous utilisez
* Vérifiez que vous disposez de la licence ONTAP appropriée


Pour configurer le LIF MetroCluster, consultez la documentation d'Astra Trident pour plus d'informations sur chaque pilote :

* https://docs.netapp.com/us-en/trident/trident-use/ontap-san-examples.html["SAN"^]
* https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html["NAS"^]




== Registre d'images

Vous devez disposer d'un registre d'images Docker privé sur lequel vous pouvez envoyer les images de build d'Astra Control Center. Vous devez fournir l'URL du registre d'images où vous allez télécharger les images.



== Licence Astra Control Center

ASTRA Control Center requiert une licence Astra Control Center. Lorsque vous installez Astra Control Center, une licence d'évaluation intégrée de 90 jours pour 4,800 UC est déjà activée. Si vous avez besoin de davantage de capacité ou de conditions d'évaluation différentes, ou si vous souhaitez effectuer une mise à niveau vers une licence complète, vous pouvez obtenir une autre licence d'évaluation ou une licence complète auprès de NetApp. Vous devez disposer d'une licence pour protéger vos applications et vos données.

Vous pouvez essayer Astra Control Center en vous inscrivant pour un essai gratuit. Vous pouvez vous inscrire en vous inscrivant link:https://bluexp.netapp.com/astra-register["ici"^].

Pour configurer la licence, reportez-vous à la section link:setup_overview.html["utilisez une licence d'essai gratuite de 90 jours"^].

Pour en savoir plus sur le fonctionnement des licences, reportez-vous à la section link:../concepts/licensing.html["Licences"^].



== Configuration réseau requise

Configurez votre environnement opérationnel pour vous assurer qu'Astra Control Center peut communiquer correctement. Les configurations réseau suivantes sont requises :

* *Adresse FQDN* : vous devez avoir une adresse FQDN pour Astra Control Center.
* *Accès à Internet* : vous devez déterminer si vous avez un accès extérieur à Internet. Si ce n'est pas le cas, certaines fonctionnalités peuvent être limitées, comme la réception de données de surveillance et de metrics depuis NetApp Cloud Insights ou l'envoi de packs de support au https://mysupport.netapp.com/site/["Site de support NetApp"^].
* *Port Access* : l'environnement opérationnel qui héberge Astra Control Center communique avec les ports TCP suivants. Veillez à ce que ces ports soient autorisés par le biais de pare-feu et configurez des pare-feu pour autoriser tout trafic de sortie HTTPS provenant du réseau Astra. Certains ports nécessitent une connectivité entre l'environnement hébergeant le centre de contrôle Astra et chaque cluster géré (le cas échéant).



NOTE: Vous pouvez déployer Astra Control Center dans un cluster Kubernetes à double pile, et Astra Control Center peut gérer les applications et les systèmes back-end de stockage qui ont été configurés pour un fonctionnement à double pile. Pour plus d'informations sur la configuration requise pour les clusters à double pile, consultez le https://kubernetes.io/docs/concepts/services-networking/dual-stack/["Documentation Kubernetes"^].

|===
| Source | Destination | Port | Protocole | Objectif 


| PC client | Centre de contrôle Astra | 443 | HTTPS | Accès à l'interface utilisateur / à l'API : assurez-vous que ce port est ouvert dans les deux sens entre Astra Control Center et le système utilisé pour accéder à Astra Control Center 


| Consommateurs de metrics | Nœud de travail Astra Control Center | 9090 | HTTPS | Communication de données de metrics : assurez-vous que chaque cluster géré peut accéder à ce port sur le cluster hébergeant Astra Control Center (communication bidirectionnelle requise). 


| Centre de contrôle Astra | Service Cloud Insights hébergé  | 443 | HTTPS | Communication avec Cloud Insights 


| Centre de contrôle Astra | Fournisseur de compartiments de stockage Amazon S3 | 443 | HTTPS | Communications de stockage Amazon S3 


| Centre de contrôle Astra | NetApp AutoSupport  | 443 | HTTPS | Communication avec NetApp AutoSupport 


| Centre de contrôle Astra | Cluster Kubernetes géré | 443/6443
*REMARQUE* : le port utilisé par le cluster géré peut varier en fonction du cluster. Consultez la documentation fournie par le fournisseur du logiciel du cluster. | HTTPS | Communication avec le cluster géré : assurez-vous que ce port est ouvert des deux manières entre le cluster hébergeant Astra Control Center et chaque cluster géré 
|===


== Entrée pour les clusters Kubernetes sur site

Vous pouvez choisir le type d'entrée de réseau utilisé par le centre de contrôle Astra. Par défaut, Astra Control Center déploie la passerelle Astra Control Center (service/trafik) comme ressource à l'échelle du cluster. Astra Control Center prend également en charge l'utilisation d'un équilibreur de charge de service, s'ils sont autorisés dans votre environnement. Si vous préférez utiliser un équilibreur de charge de service et que vous n'avez pas encore configuré, vous pouvez utiliser l'équilibreur de charge MetalLB pour attribuer automatiquement une adresse IP externe au service. Dans la configuration du serveur DNS interne, pointez le nom DNS choisi pour Astra Control Center vers l'adresse IP à équilibrage de charge.


NOTE: L'équilibreur de charge doit utiliser une adresse IP située dans le même sous-réseau que les adresses IP du nœud de travail de l'Astra Control Center.

Pour plus d'informations, reportez-vous à la section link:../get-started/install_acc.html#set-up-ingress-for-load-balancing["Configurer l'entrée pour l'équilibrage de charge"^].



=== Exigences d'entrée de Google Anthos

Lorsque vous hébergez Astra Control Center sur un cluster Google Anthos, notez que Google Anthos inclut par défaut l'équilibreur de charge MetalLB et le service d'entrée Istio, ce qui vous permet d'utiliser simplement les fonctionnalités d'entrée génériques d'Astra Control Center lors de l'installation. Reportez-vous à la section link:install_acc.html#configure-astra-control-center["Configurer le centre de contrôle Astra"^] pour plus d'informations.



== Navigateurs Web pris en charge

Astra Control Center prend en charge les versions récentes de Firefox, Safari et Chrome avec une résolution minimale de 1280 x 720.



== Exigences supplémentaires relatives aux clusters d'applications

Gardez à l'esprit ces exigences si vous prévoyez d'utiliser ces caractéristiques du centre de contrôle Astra :

* *Configuration requise pour le cluster d'applications* : link:../get-started/setup_overview.html#prepare-your-environment-for-cluster-management-using-astra-control["Exigences de gestion du cluster"^]
+
** * Exigences des applications gérées* : link:../use/manage-apps.html#application-management-requirements["De gestion des applications"^]
** *Exigences supplémentaires pour la réplication d'applications* : link:../use/replicate_snapmirror.html#replication-prerequisites["Conditions préalables à la réplication"^]






== Et la suite

Afficher le link:quick-start.html["démarrage rapide"^] présentation.
